# Extract location/channel IDs from Expedia test.csv

Минимальная выгрузка ID-полей для последующего маппинга на реальные названия.

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
DATA_PATH = Path('data/test.csv')
OUT_PATH = Path('test_location_ids.csv')

In [3]:
cols = [
    'posa_continent',
    'user_location_country',
    'user_location_region',
    'user_location_city',
    'channel',
    'hotel_continent',
    'hotel_country',
    'hotel_market',
]

df = pd.read_csv(DATA_PATH, usecols=cols)
df.head()

,posa_continent,user_location_country,user_location_region,user_location_city,channel,hotel_continent,hotel_country,hotel_market
0,3,66,174,37449,3,6,204,27
1,3,66,174,37449,10,6,204,1540
2,3,66,142,17440,1,2,50,699
3,3,66,258,34156,10,2,50,628
4,3,66,467,36345,0,2,50,538

In [4]:
df.shape, df.isna().sum()

((2528243, 8),
 posa_continent           0
 user_location_country    0
 user_location_region     0
 user_location_city       0
 channel                  0
 hotel_continent          0
 hotel_country            0
 hotel_market             0
 dtype: int64)

In [5]:
df.nunique().sort_values(ascending=False)

user_location_city       36722
hotel_market              2115
user_location_region       988
user_location_country      236
hotel_country              206
channel                     11
hotel_continent              7
posa_continent               5
dtype: int64

In [6]:
df.to_csv(OUT_PATH, index=False)
OUT_PATH

PosixPath('test_location_ids.csv')

## Optional: unique ID combinations

Если аналитикам не нужны все строки, можно передать только уникальные комбинации.

In [7]:
unique_ids = df.drop_duplicates().reset_index(drop=True)
unique_ids.to_csv('test_location_ids_unique.csv', index=False)
unique_ids.head()

,posa_continent,user_location_country,user_location_region,user_location_city,channel,hotel_continent,hotel_country,hotel_market
0,3,66,174,37449,3,6,204,27
1,3,66,174,37449,10,6,204,1540
2,3,66,142,17440,1,2,50,699
3,3,66,258,34156,10,2,50,628
4,3,66,467,36345,0,2,50,538

In [8]:
unique_ids.shape

(1452111, 8)